version: "3"

services:
  media-toolkit:
    build: .
    image: m4heshd/media-toolkit
    container_name: media-toolkit
    restart: no
    environment:
      TTYD_ENABLED: "1"
    ports:
      - "8585:2525" # ttyd web-ui
      - "2222:22" # SSH
    volumes:
      - ./ssh/my_public_key.pub:/config/ssh/key.pub # Public key you want to use to access this container via SSH
      - ./fonts:/usr/share/fonts/custom # Custom fonts that your subtitles burn-in process might require
      - ~/Videos:/data # Media files you plan to process with subs-burner
