name: release

on:
  release:
    types:
      - released

jobs:
  docker-publish:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4
      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Authenticate Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build docker image and push to Docker Hub repo
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            m4heshd/media-toolkit:${{ github.event.release.tag_name }}
            m4heshd/media-toolkit:latest
      # Update Docker Hub repo description
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: m4heshd/media-toolkit
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}
